### ISSUE TITLE
New players not appearing on leader-boards

### ISSUE THREAD

**Issue by ghost** [djrscally/pubg_reporting#17]
I currently pull out match and season data into metabase leader-boards. Yesterday I added a few new players to my included players table and updated the names of a few existing ones. These new players don't seem to be appearing in my leader-boards (season stats based), the updated name ones are.

I also have a leader-board pulling from match data for specific matches, the new and updated name players are not showing on there.

**Comment by djrscally** [comment]
What's happening here is the current season is not pulled for players who haven't played any matches since the last sync happened. Once they play a match, they will be pulled. I'll amend the logic so current season is included in the "if not exists" pull.
