### ISSUE TITLE
Season Stats don't refresh

### ISSUE THREAD

**Issue by ghost** [djrscally/pubg_reporting#19]
Hi there,

by running data the table player_season_stats will not be updated until i change Last Sync Datetime to a date in the past.

**Comment by djrscally** [comment]
Hey dude - sorry for the delay, I'm away for a few days. Can you elaborate a little? The sync should set the last sync datetime to the current time when it completes. is that not happening for you or something? The only time we've seen it have problems is where people are added and then don't play for a few days and it won't pull them till they do.
