### ISSUE TITLE
new installation on windows doesn't work

### ISSUE THREAD

**Issue by Devastatin** [djrscally/pubg_reporting#26]
Enviornment variables are set, software installed locally.  Recieve this error

`
PS D:\pubg_reporting> & D:/Python/python.exe d:/pubg_reporting/sync.py
D:\Python\lib\site-packages\sqlalchemy\dialects\mysql\base.py:1308: SAWarning: Additional column names not matching any column keys in table 'players': 'status'
  util.warn(
D:\Python\lib\site-packages\pymysql\cursors.py:170: Warning: (1287, "'VALUES function' is deprecated and will be removed in a future release. Please use an alias (INSERT INTO ... VALUES (...) AS alias) and replace VALUES(col) in the ON DUPLICATE KEY UPDATE clause with alias.col instead")
  result = self._query(query)
Traceback (most recent call last):
  File "d:/pubg_reporting/sync.py", line 219, in <module>
    sync()
  File "D:\Python\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "D:\Python\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "D:\Python\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Python\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:/pubg_reporting/sync.py", line 59, in sync
    __sync(api, pubgdb)
  File "d:/pubg_reporting/sync.py", line 187, in __sync
    api.get_player_season_stats(combo)
  File "d:\pubg_reporting\pubg\pubg_api.py", line 200, in get_player_season_stats
    logging.debug("get_player_season_stats: {0}: {1}: {2}".format(combo[0], combo[1], json.dumps(r.json()['data']['attributes']['gameModeStats'], indent=4)))
KeyError: 'data'
PS D:\pubg_reporting> `

it looks like it created some tables, but was unable to finish the job

**Comment by djrscally** [comment]
Did you pull master from recently? If so try again and see if it works now?
When there's a keyerror like that it's usually an indication that the API
calls failed for some reason, which could just be a temporary issue

**Comment by Devastatin** [comment]
Same Error, 

To make sure it wasn't an API error.

just re-downloaded entire repo to a new location, added my config.json in the right spot

I dropped all the tables and rebuilt using 

results from mysql.

`
mysql> show tables;
Empty set (0.00 sec)
`

`D:\pubg_reporting>sync.py --build-only`
`
mysql> show tables;
+-----------------------+
| Tables_in_pubg        |
+-----------------------+
| matches               |
| player_lifetime_stats |
| player_match_stats    |
| player_matches        |
| player_season_stats   |
| players               |
| season_matches        |
| seasons               |
| system_information    |
+-----------------------+
9 rows in set (0.00 sec)
`
`mysql> select * from seasons;
Empty set (0.00 sec)`
`
D:\pubg_reporting>sync.py
`D:\Python\lib\site-packages\sqlalchemy\dialects\mysql\base.py:1308: SAWarning: Additional column names not matching any column keys in table 'players': 'status'
  util.warn(
D:\Python\lib\site-packages\pymysql\cursors.py:170: Warning: (1287, "'VALUES function' is deprecated and will be removed in a future release. Please use an alias (INSERT INTO ... VALUES (...) AS alias) and replace VALUES(col) in the ON DUPLICATE KEY UPDATE clause with alias.col instead")
  result = self._query(query)
Traceback (most recent call last):
  File "D:\pubg_reporting\sync.py", line 219, in <module>
    sync()
  File "D:\Python\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "D:\Python\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "D:\Python\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Python\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "D:\pubg_reporting\sync.py", line 59, in sync
    __sync(api, pubgdb)
  File "D:\pubg_reporting\sync.py", line 187, in __sync
    api.get_player_season_stats(combo)
  File "D:\pubg_reporting\pubg\pubg_api.py", line 200, in get_player_season_stats
    logging.debug("get_player_season_stats: {0}: {1}: {2}".format(combo[0], combo[1], json.dumps(r.json()['data']['attributes']['gameModeStats'], indent=4)))
KeyError: 'data'`

`mysql> select * from seasons;
+----------------------------------+-------------------+---------------+
| season_id                        | is_current_season | is_off_season |
+----------------------------------+-------------------+---------------+
| division.bro.official.2017-beta  |                 0 |             0 |
| division.bro.official.2017-pre1  |                 0 |             0 |
| division.bro.official.2017-pre2  |                 0 |             0 |
| division.bro.official.2017-pre3  |                 0 |             0 |
| division.bro.official.2017-pre4  |                 0 |             0 |
| division.bro.official.2017-pre5  |                 0 |             0 |
| division.bro.official.2017-pre6  |                 0 |             0 |
| division.bro.official.2017-pre7  |                 0 |             0 |
| division.bro.official.2017-pre8  |                 0 |             0 |
| division.bro.official.2017-pre9  |                 0 |             0 |
| division.bro.official.2018-01    |                 0 |             0 |
| division.bro.official.2018-02    |                 0 |             0 |
| division.bro.official.2018-03    |                 0 |             0 |
| division.bro.official.2018-04    |                 0 |             0 |
| division.bro.official.2018-05    |                 0 |             0 |
| division.bro.official.2018-06    |                 0 |             0 |
| division.bro.official.2018-07    |                 0 |             0 |
| division.bro.official.2018-08    |                 0 |             0 |
| division.bro.official.2018-09    |                 0 |             0 |
| division.bro.official.pc-2018-01 |                 0 |             0 |
| division.bro.official.pc-2018-02 |                 0 |             0 |
| division.bro.official.pc-2018-03 |                 0 |             0 |
| division.bro.official.pc-2018-04 |                 0 |             0 |
| division.bro.official.pc-2018-05 |                 0 |             0 |
| division.bro.official.pc-2018-06 |                 0 |             0 |
| division.bro.official.pc-2018-07 |                 1 |             0 |
+----------------------------------+-------------------+---------------+
26 rows in set (0.00 sec)
'

**Comment by Devastatin** [comment]
Pulled another branch of the code and got it to work with a few tweaks.

**Comment by djrscally** [comment]
Good news but it's good if we can fix your problem in master too. What did
you tweak?

**Comment by Devastatin** [comment]
I think I found the issue, I'm learning Python (know quite a few other languages, but this one is new). 

The results from the API are not consistent for season 7
for all seasons prior to 6 get_player_season_stats (Line 225 of pubg_api.py for the current master version) its in this order. {
  "data": {
    "type": "playerSeason",
    "attributes": {
      "gameModeStats": {


https://api.pubg.com/shards/steam/players/account.f52537ea599a44d0a402305582738402/seasons/division.bro.official.pc-2018-06
Shown with this API call.

For seasons 7 it pulls

for 07 its {
  "data": {
    "type": "playerSeason",
    "attributes": {
      **"bestRankPoint": 0,**
      "gameModeStats": {


https://api.pubg.com/shards/steam/players/account.f52537ea599a44d0a402305582738402/seasons/division.bro.official.pc-2018-07

Which breaks the line 

logging.debug("get_player_season_stats: {0}: {1}: {2}".format(combo[0], combo[1], json.dumps(r.json()['data']['attributes']['gameModeStats'], indent=4)))

I know almost nothing about json (maybe 4 days of experience) and maybe a week of looking at python code. I honestly fixed it by yanking out the gamemodestats and doesn't seem to result in the fix id want. The other piece i changed looks like isn't an issue in the master version.

**Comment by djrscally** [comment]
The order of the fields doesn't matter; I'm treating the returned string as json; where it's a multi-item array I'm looping over it (which implicitly accesses the elements by index) but to access each individual actual field I use the key, so the order doesn't matter at all there.

The line you've listed is just dropping the contents of the API payload into the logging file so that it's easier to debug; it's not actually trying to access the data.

The error message "KeyError: 'data'" is saying that the API isn't returning a json payload of data, it's returning something else. In retrospect it was stupid of me to assume that the payload would still be there for debugging, since half the problems I've had have been with HTTP errors not returning the payload. I've made a new commit to master that removes the attempt to navigate through the data structure, so that error should clear. Note if you pull it I also made a bunch of other changes, including adding new tables to the database, so you should read the "upgrading to a new version of the code" bit on the README.

What it probably won't do is fix your issue, because the underlying problem is that you're getting some other response than 200 from the API. Can you maybe either look in sync.log after a run where you get the error (CTRL-F for "Beginning get_player_season_stats() call" and it should jump to that section. Alternatively attach the logs as a gist or something so i can take a look?

**Comment by Devastatin** [comment]
around line 227 of pubg_api.py

        ## Only allow Valid requests to be parsed
        if r.status_code == 200:
            self.player_season_stats.append(
                r.json()['data']
            )

It was sending 200 and 404 errors (no idea why it was doing it for some and not others).
Also, haven't been able to get logging to work outside of print (r.status_code) to stdout. Shrug, one little thing at a time.

I'm trying to figureout how to do a pull request (gosh i hope thats the right term).

**Comment by Devastatin** [comment]
as soon as i say that, i figure out that it requires switches. =\ I need to RTFM a little more. My little code tweak permanently fixes this section so it doesn't crash, it skips any status code other than 429. Full detailed log below. 
[sync.log](https://github.com/djrscally/pubg_reporting/files/4711774/sync.log)

**Comment by djrscally** [comment]
I'll take a look in a couple hours and see if I can figure out the problem.
To submit a PR you'd need to fork this repo and commit to the master branch
of your own fork; there should then be a button to submit a pull request
back to this repo.

Switching things to only try and process responses when the http response
is a 200 is definitely a good idea, we'd also need to have the logger write
exceptions so it's flagged there that something broke.

**Comment by djrscally** [comment]
So here's why things are confused:

```
2020-06-01 10:21:41,300:DEBUG:Starting new HTTPS connection (1): api.pubg.com:443
2020-06-01 10:21:41,420:DEBUG:https://api.pubg.com:443 "GET /shards/steam/players/account.f52537ea599a44d0a402305582738402/seasons/division.bro.official.2017-beta HTTP/1.1" 404 83
2020-06-01 10:21:41,422:DEBUG:get_player_season_stats: account.f52537ea599a44d0a402305582738402: division.bro.official.2017-beta: {
    "errors": [
        {
            "title": "Not Found",
            "detail": "No Season Stats Found"
        }
    ]
}
```

When you call get_player_season_stats() for a season that the player _has not played in_, you're getting a HTTP 404 response plus a JSON payload that says so. The guy I built this for plays xbox, and using that shard that's not what happens; for the xbox shard you just get a normal response but with all the values set to 0.

Yay for consistent functionality.

So yeah; to solve I think the patch you've applied is along the right lines. I'm going to review it now.
